[package]
name = "macro-define"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1"
syn = {features = ["full", "extra-traits"]}

[lib]
proc-macro = true
